general {
  lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  timeout = 480
  on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  timeout = 180
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
