# BACKGROUND
background {
    monitor = HDMI-A-1
    #path = screenshot
    path = /home/hmuy/Documents/lockscreen.jpg
    #color = $background
    blur_passes = 0
    contrast = 1
    brightness = 1
    vibrancy = 1
    vibrancy_darkness = 0.2
}

background {
    monitor = eDP-1
    #path = screenshot
    path = /home/hmuy/Documents/lockscreen2.jpg
    #color = $background
    blur_passes = 0
    contrast = 1
    brightness = 1
    vibrancy = 1
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = false
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = :3
    fingerprint:present_message = ewwwwwwww
}

# INPUT FIELD
input-field {
    monitor =
    size = 275, 60
    outline_thickness = -1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(205, 214, 244, 1)
    fade_on_empty = false
    rounding = 5
    check_color = rgb(205, 214, 244)
    fail_color = rgb(243, 139, 168)
    placeholder_text = <span foreground="##cdd6f4">hmuy</span>
    fail_text = <span>nuh uh</span>
    hide_input = false
    position = 60, 100
    halign = right
    valign = bottom
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = SFProDisplay Nerd Font
  position = 35, 125
  halign = left
  valign = bottom
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = SFProDisplay Nerd Font
  position = 25, 150
  halign = left
  valign = bottom
}



# Profile Picture
image {
    monitor =
    path = /home/hmuy/Pictures/aaaaa.jpg
    size = 100
    border_size = 2
    border_color = $foreground
    position = -25, 150
    halign = right
    valign = bottom
}
