# BACKGROUND
background {
    monitor = 
    path = /home/hmuy/Documents/lockscreen.png
    blur_passes = 1
    contrast = 0.8
    brightness = 0.8
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = :3
    fingerprint:present_message = ewwwwwwww
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = -1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(205, 214, 244, 1)
    fade_on_empty = false
    rounding = 5
    check_color = rgb(205, 214, 244)
    fail_color = rgb(243, 139, 168)
    placeholder_text = <span foreground="##cdd6f4">hmuy</span>
    fail_text = <span>nuh uh</span>
    font_family = SFRounded Nerd Font
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = SFRounded Nerd Font
  position = 0, 350
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 1)
  font_size = 95
  font_family = SFRounded Nerd Font Bold
  position = 0, 250
  halign = center
  valign = center
}



# Profile Picture
image {
    monitor =
    path = /home/hmuy/Pictures/aaaaa.png
    size = 125
    border_size = 2
    border_color = #4d4463
    position = 0, -100
    halign = center
    valign = center
}
