input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_rules =
    kb_options = ctrl:nocaps

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0.4 # -1.0 - 1.0, 0 means no modification.
}

xwayland {
  force_zero_scaling = true
}

misc {
    disable_hyprland_logo=false
    vfr=true
}

ecosystem {
    no_update_news=true
    no_donation_nag=true
}