layerrule {
  name = layerrule-1
  blur = on
  match:namespace = waybar
}

windowrule {
  name = windowrule-1
  float = on
  pin = on
  match:class = zenity
}


windowrule {
  name = windowrule-2
  opacity = 0.9 override 0.9 override
  border_size = 0
  match:title = (.*)
}

windowrule {
  name = windowrule-3
  opacity = 1 override 1 override
  match:class = chromium|com.github.iwalton3.jellyfin-media-player
}

windowrule {
  name = windowrule-4
  opacity = 0.85 override 0.8 override
  match:class = kitty|code-insiders|org.gnome.Nautilus
}

windowrule {
  name = windowrule-5
  opacity = 1 override 1 override
  tile = on
  match:initial_class = steam_app_2325290
}
