layerrule = blur, waybar
windowrule = float,class:zenity
windowrule = pin,class:zenity

windowrule = opacity 0.9 override 0.9 override, title:(.*)
windowrule = opacity 1 override 1 override, class:chromium|com.github.iwalton3.jellyfin-media-player
windowrule = opacity 0.8 override 0.8 override, class:kitty|code-insiders|vesktop|org.gnome.Nautilus
windowrule = noborder, title:(.*)
windowrule = opacity 1 override 1 override, initialClass:steam_app_2325290
windowrule = tile, initialClass:steam_app_2325290